# Generated by Django 5.2.7 on 2025-11-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
