# Generated by Django 5.2.7 on 2025-11-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_purchaseinvoice_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobwork',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
