# Generated by Django 5.2.7 on 2025-11-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_jobwork_balance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
