# Generated by Django 5.2.7 on 2025-11-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_purchaseitem_supplier_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftsmanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='craftsman_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('jobwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='master.jobwork')),
            ],
        ),
    ]
