# Generated by Django 5.2.7 on 2025-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_craftsmanattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
