# Generated by Django 5.2.7 on 2025-11-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_loan_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='bill_type',
            field=models.CharField(choices=[('GST', 'GST'), ('Estimate', 'Estimate')], default='GST', max_length=20),
        ),
    ]
