# Generated by Django 5.2.7 on 2025-11-11 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_saleitem_bill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='URDAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjust_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adjust_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adjust_hm_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urd_adjustment', to='master.saleitem')),
            ],
        ),
        migrations.CreateModel(
            name='URDDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('pieces', models.PositiveIntegerField(default=0)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('less_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('comments', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='urd_files/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urd_details', to='master.saleitem')),
            ],
        ),
    ]
