# Generated by Django 5.2.7 on 2025-11-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_urdadjustment_urddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='urddetail',
            name='urd_adjustment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='urd_details', to='master.urdadjustment'),
            preserve_default=False,
        ),
    ]
