# Generated by Django 5.2.7 on 2025-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_urddetail_urd_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
