# Generated by Django 5.2.7 on 2025-11-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_alter_loan_gross_weight_alter_loan_purity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
