# Generated by Django 5.2.7 on 2025-11-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_alter_loanpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempayment',
            name='urd_exchange_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
