# Generated by Django 5.2.7 on 2025-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_itempayment_urd_exchange_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='purity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
