# Generated by Django 5.2.7 on 2025-11-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master.purchaseinvoice'),
        ),
    ]
