# Generated by Django 5.2.7 on 2025-11-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='urd_purity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
