# Generated by Django 5.2.7 on 2025-12-08 07:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_order_urd_purity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhishi_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bhishi_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=50, null=True)),
                ('bhishi_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_installments', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bhishis', to='master.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BhishiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bhishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='master.bhishi')),
            ],
        ),
    ]
