# Generated by Django 5.2.7 on 2025-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_bhishi_bhishipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='final_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
