# Generated by Django 5.2.7 on 2025-12-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_jewelry_final_amount_jewelry_final_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamonddetail',
            name='clarity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diamonddetail',
            name='fluorescence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diamonddetail',
            name='polish',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diamonddetail',
            name='shape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diamonddetail',
            name='symmetry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BhishiInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bhishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='master.bhishi')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('bhishi', 'installment_number')},
            },
        ),
    ]
