# Generated by Django 5.2.7 on 2025-12-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_diamonddetail_clarity_diamonddetail_fluorescence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supplier_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='master.purchaseinvoice')),
            ],
        ),
    ]
