# Generated by Django 5.2.7 on 2026-01-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_order_urd_item_name_order_urd_metal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='purity',
            field=models.CharField(max_length=20),
        ),
    ]
