# Generated by Django 5.2.7 on 2026-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_alter_jewelry_purity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='purity',
            field=models.CharField(max_length=20),
        ),
    ]
