# Generated by Django 5.2.7 on 2026-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_alter_saleitem_purity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='urd_purity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='purity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
