# Generated by Django 5.2.7 on 2026-01-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_alter_order_urd_purity_alter_orderitem_purity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobwork',
            name='purity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
