# Generated by Django 5.2.7 on 2026-01-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_alter_jobwork_purity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamondmetalinfo',
            name='purity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='purity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='purity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
