# Generated by Django 5.2.7 on 2026-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_alter_diamondmetalinfo_purity_alter_jewelry_purity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
