# Generated by Django 5.2.7 on 2026-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0031_orderitem_length_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
