# Generated by Django 5.2.7 on 2026-03-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0032_orderitem_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='advance_gold_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
