# Generated by Django 5.2.7 on 2026-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0033_orderitem_advance_gold_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
