# Generated by Django 5.2.7 on 2026-04-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0034_loan_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='saleitem_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
