# Generated by Django 5.2.7 on 2026-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0035_saleitem_saleitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='order_attachments/'),
        ),
    ]
