# Generated by Django 5.2.7 on 2026-04-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0037_alter_order_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='order_attachments/'),
        ),
    ]
