# Generated by Django 5.2.7 on 2026-04-11 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0039_loanattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhishiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bhishi_attachments/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bhishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='master.bhishi')),
            ],
        ),
    ]
