# Generated by Django 5.2.7 on 2026-07-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0041_installmentattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCompletionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='loan_completion_attachments/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('certificate', 'Certificate'), ('document', 'Document'), ('other', 'Other')], default='document', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_attachments', to='master.loan')),
            ],
            options={
                'verbose_name': 'Loan Completion Attachment',
                'verbose_name_plural': 'Loan Completion Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
